//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioDatos
{
    using ServicioModelo.Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlCalidadEntities1 : DbContext
    {
        public ControlCalidadEntities1()
            : base("name=ControlCalidadEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alerta> Alerta { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Defecto> Defecto { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EstadoOrden> EstadoOrden { get; set; }
        public virtual DbSet<JornadaLaboral> JornadaLaboral { get; set; }
        public virtual DbSet<Linea> Linea { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<OrdenProduccion> OrdenProduccion { get; set; }
        public virtual DbSet<Pie> Pie { get; set; }
        public virtual DbSet<Registro> Registro { get; set; }
        public virtual DbSet<Semaforo> Semaforo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoDefecto> TipoDefecto { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
    }
}
