//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioModelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public int IdAlerta { get; set; }
        public Nullable<System.DateTime> FechaHoraDetiene { get; set; }
        public Nullable<System.DateTime> FechaHoraReinicio { get; set; }
        public Nullable<int> IdSemaforo { get; set; }
        public Nullable<int> IdTipoDefecto { get; set; }
        public Nullable<int> IdOrdenProduccion { get; set; }
    
        public virtual OrdenProduccion OrdenProduccion { get; set; }
        public virtual Semaforo Semaforo { get; set; }
        public virtual TipoDefecto TipoDefecto { get; set; }
    }
}
