//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioModelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenProduccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenProduccion()
        {
            this.Alerta = new HashSet<Alerta>();
            this.JornadaLaboral = new HashSet<JornadaLaboral>();
        }
    
        public int IdOrdenProduccion { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> IdColor { get; set; }
        public Nullable<int> IdModelo { get; set; }
        public Nullable<int> IdEstadoOrden { get; set; }
        public Nullable<int> IdLinea { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerta> Alerta { get; set; }
        public virtual Color Color { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual EstadoOrden EstadoOrden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JornadaLaboral> JornadaLaboral { get; set; }
        public virtual Linea Linea { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
