//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioModelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int IdRegistro { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<int> IdDefecto { get; set; }
        public Nullable<int> IdPie { get; set; }
        public Nullable<int> IdJornadaLaboral { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Defecto Defecto { get; set; }
        public virtual JornadaLaboral JornadaLaboral { get; set; }
        public virtual Pie Pie { get; set; }
    }
}
